// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "qonto-bulk-transfer/internal/transfer/model"

	mock "github.com/stretchr/testify/mock"

	service "qonto-bulk-transfer/internal/transfer/service"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ListTransactionHistory provides a mock function with given fields: ctx, accountID, cursor, limit
func (_m *MockService) ListTransactionHistory(ctx context.Context, accountID int64, cursor string, limit int) (service.TransactionHistoryPage, error) {
	ret := _m.Called(ctx, accountID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactionHistory")
	}

	var r0 service.TransactionHistoryPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int) (service.TransactionHistoryPage, error)); ok {
		return rf(ctx, accountID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int) service.TransactionHistoryPage); ok {
		r0 = rf(ctx, accountID, cursor, limit)
	} else {
		r0 = ret.Get(0).(service.TransactionHistoryPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int) error); ok {
		r1 = rf(ctx, accountID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListTransactionHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactionHistory'
type MockService_ListTransactionHistory_Call struct {
	*mock.Call
}

// ListTransactionHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
//   - cursor string
//   - limit int
func (_e *MockService_Expecter) ListTransactionHistory(ctx interface{}, accountID interface{}, cursor interface{}, limit interface{}) *MockService_ListTransactionHistory_Call {
	return &MockService_ListTransactionHistory_Call{Call: _e.mock.On("ListTransactionHistory", ctx, accountID, cursor, limit)}
}

func (_c *MockService_ListTransactionHistory_Call) Run(run func(ctx context.Context, accountID int64, cursor string, limit int)) *MockService_ListTransactionHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockService_ListTransactionHistory_Call) Return(_a0 service.TransactionHistoryPage, _a1 error) *MockService_ListTransactionHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListTransactionHistory_Call) RunAndReturn(run func(context.Context, int64, string, int) (service.TransactionHistoryPage, error)) *MockService_ListTransactionHistory_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitBulkTransfer provides a mock function with given fields: ctx, req
func (_m *MockService) SubmitBulkTransfer(ctx context.Context, req model.BulkTransferRequest) (service.Result, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SubmitBulkTransfer")
	}

	var r0 service.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BulkTransferRequest) (service.Result, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BulkTransferRequest) service.Result); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(service.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BulkTransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_SubmitBulkTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitBulkTransfer'
type MockService_SubmitBulkTransfer_Call struct {
	*mock.Call
}

// SubmitBulkTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.BulkTransferRequest
func (_e *MockService_Expecter) SubmitBulkTransfer(ctx interface{}, req interface{}) *MockService_SubmitBulkTransfer_Call {
	return &MockService_SubmitBulkTransfer_Call{Call: _e.mock.On("SubmitBulkTransfer", ctx, req)}
}

func (_c *MockService_SubmitBulkTransfer_Call) Run(run func(ctx context.Context, req model.BulkTransferRequest)) *MockService_SubmitBulkTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BulkTransferRequest))
	})
	return _c
}

func (_c *MockService_SubmitBulkTransfer_Call) Return(_a0 service.Result, _a1 error) *MockService_SubmitBulkTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_SubmitBulkTransfer_Call) RunAndReturn(run func(context.Context, model.BulkTransferRequest) (service.Result, error)) *MockService_SubmitBulkTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
