// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// Atomic provides a mock function with given fields: ctx, fn
func (_m *MockTransactor) Atomic(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Atomic")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactor_Atomic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Atomic'
type MockTransactor_Atomic_Call struct {
	*mock.Call
}

// Atomic is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockTransactor_Expecter) Atomic(ctx interface{}, fn interface{}) *MockTransactor_Atomic_Call {
	return &MockTransactor_Atomic_Call{Call: _e.mock.On("Atomic", ctx, fn)}
}

func (_c *MockTransactor_Atomic_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockTransactor_Atomic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockTransactor_Atomic_Call) Return(_a0 error) *MockTransactor_Atomic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactor_Atomic_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockTransactor_Atomic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
