// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "qonto-bulk-transfer/internal/transfer/model"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AdvisoryLock provides a mock function with given fields: ctx, key
func (_m *MockRepository) AdvisoryLock(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for AdvisoryLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AdvisoryLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvisoryLock'
type MockRepository_AdvisoryLock_Call struct {
	*mock.Call
}

// AdvisoryLock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRepository_Expecter) AdvisoryLock(ctx interface{}, key interface{}) *MockRepository_AdvisoryLock_Call {
	return &MockRepository_AdvisoryLock_Call{Call: _e.mock.On("AdvisoryLock", ctx, key)}
}

func (_c *MockRepository_AdvisoryLock_Call) Run(run func(ctx context.Context, key string)) *MockRepository_AdvisoryLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_AdvisoryLock_Call) Return(_a0 error) *MockRepository_AdvisoryLock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AdvisoryLock_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_AdvisoryLock_Call {
	_c.Call.Return(run)
	return _c
}

// DebitAccount provides a mock function with given fields: ctx, accountID, amountCents
func (_m *MockRepository) DebitAccount(ctx context.Context, accountID int64, amountCents int64) (int64, error) {
	ret := _m.Called(ctx, accountID, amountCents)

	if len(ret) == 0 {
		panic("no return value specified for DebitAccount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (int64, error)); ok {
		return rf(ctx, accountID, amountCents)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = rf(ctx, accountID, amountCents)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, accountID, amountCents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_DebitAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebitAccount'
type MockRepository_DebitAccount_Call struct {
	*mock.Call
}

// DebitAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
//   - amountCents int64
func (_e *MockRepository_Expecter) DebitAccount(ctx interface{}, accountID interface{}, amountCents interface{}) *MockRepository_DebitAccount_Call {
	return &MockRepository_DebitAccount_Call{Call: _e.mock.On("DebitAccount", ctx, accountID, amountCents)}
}

func (_c *MockRepository_DebitAccount_Call) Run(run func(ctx context.Context, accountID int64, amountCents int64)) *MockRepository_DebitAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockRepository_DebitAccount_Call) Return(_a0 int64, _a1 error) *MockRepository_DebitAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_DebitAccount_Call) RunAndReturn(run func(context.Context, int64, int64) (int64, error)) *MockRepository_DebitAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FindAccountForUpdate provides a mock function with given fields: ctx, iban, bic
func (_m *MockRepository) FindAccountForUpdate(ctx context.Context, iban string, bic string) (model.Account, bool, error) {
	ret := _m.Called(ctx, iban, bic)

	if len(ret) == 0 {
		panic("no return value specified for FindAccountForUpdate")
	}

	var r0 model.Account
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Account, bool, error)); ok {
		return rf(ctx, iban, bic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Account); ok {
		r0 = rf(ctx, iban, bic)
	} else {
		r0 = ret.Get(0).(model.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, iban, bic)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, iban, bic)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_FindAccountForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAccountForUpdate'
type MockRepository_FindAccountForUpdate_Call struct {
	*mock.Call
}

// FindAccountForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - iban string
//   - bic string
func (_e *MockRepository_Expecter) FindAccountForUpdate(ctx interface{}, iban interface{}, bic interface{}) *MockRepository_FindAccountForUpdate_Call {
	return &MockRepository_FindAccountForUpdate_Call{Call: _e.mock.On("FindAccountForUpdate", ctx, iban, bic)}
}

func (_c *MockRepository_FindAccountForUpdate_Call) Run(run func(ctx context.Context, iban string, bic string)) *MockRepository_FindAccountForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_FindAccountForUpdate_Call) Return(_a0 model.Account, _a1 bool, _a2 error) *MockRepository_FindAccountForUpdate_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_FindAccountForUpdate_Call) RunAndReturn(run func(context.Context, string, string) (model.Account, bool, error)) *MockRepository_FindAccountForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdempotencyRecordStatus provides a mock function with given fields: ctx, key
func (_m *MockRepository) FindIdempotencyRecordStatus(ctx context.Context, key string) (int, bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for FindIdempotencyRecordStatus")
	}

	var r0 int
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_FindIdempotencyRecordStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdempotencyRecordStatus'
type MockRepository_FindIdempotencyRecordStatus_Call struct {
	*mock.Call
}

// FindIdempotencyRecordStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRepository_Expecter) FindIdempotencyRecordStatus(ctx interface{}, key interface{}) *MockRepository_FindIdempotencyRecordStatus_Call {
	return &MockRepository_FindIdempotencyRecordStatus_Call{Call: _e.mock.On("FindIdempotencyRecordStatus", ctx, key)}
}

func (_c *MockRepository_FindIdempotencyRecordStatus_Call) Run(run func(ctx context.Context, key string)) *MockRepository_FindIdempotencyRecordStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindIdempotencyRecordStatus_Call) Return(_a0 int, _a1 bool, _a2 error) *MockRepository_FindIdempotencyRecordStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_FindIdempotencyRecordStatus_Call) RunAndReturn(run func(context.Context, string) (int, bool, error)) *MockRepository_FindIdempotencyRecordStatus_Call {
	_c.Call.Return(run)
	return _c
}

// InsertBatch provides a mock function with given fields: ctx, accountID, idempotencyKey, totalCents
func (_m *MockRepository) InsertBatch(ctx context.Context, accountID int64, idempotencyKey string, totalCents int64) (int64, error) {
	ret := _m.Called(ctx, accountID, idempotencyKey, totalCents)

	if len(ret) == 0 {
		panic("no return value specified for InsertBatch")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) (int64, error)); ok {
		return rf(ctx, accountID, idempotencyKey, totalCents)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) int64); ok {
		r0 = rf(ctx, accountID, idempotencyKey, totalCents)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = rf(ctx, accountID, idempotencyKey, totalCents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_InsertBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBatch'
type MockRepository_InsertBatch_Call struct {
	*mock.Call
}

// InsertBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
//   - idempotencyKey string
//   - totalCents int64
func (_e *MockRepository_Expecter) InsertBatch(ctx interface{}, accountID interface{}, idempotencyKey interface{}, totalCents interface{}) *MockRepository_InsertBatch_Call {
	return &MockRepository_InsertBatch_Call{Call: _e.mock.On("InsertBatch", ctx, accountID, idempotencyKey, totalCents)}
}

func (_c *MockRepository_InsertBatch_Call) Run(run func(ctx context.Context, accountID int64, idempotencyKey string, totalCents int64)) *MockRepository_InsertBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockRepository_InsertBatch_Call) Return(_a0 int64, _a1 error) *MockRepository_InsertBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_InsertBatch_Call) RunAndReturn(run func(context.Context, int64, string, int64) (int64, error)) *MockRepository_InsertBatch_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransactions provides a mock function with given fields: ctx, accountID, batchID, transfers
func (_m *MockRepository) InsertTransactions(ctx context.Context, accountID int64, batchID int64, transfers []model.CreditTransfer) error {
	ret := _m.Called(ctx, accountID, batchID, transfers)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, []model.CreditTransfer) error); ok {
		r0 = rf(ctx, accountID, batchID, transfers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_InsertTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransactions'
type MockRepository_InsertTransactions_Call struct {
	*mock.Call
}

// InsertTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
//   - batchID int64
//   - transfers []model.CreditTransfer
func (_e *MockRepository_Expecter) InsertTransactions(ctx interface{}, accountID interface{}, batchID interface{}, transfers interface{}) *MockRepository_InsertTransactions_Call {
	return &MockRepository_InsertTransactions_Call{Call: _e.mock.On("InsertTransactions", ctx, accountID, batchID, transfers)}
}

func (_c *MockRepository_InsertTransactions_Call) Run(run func(ctx context.Context, accountID int64, batchID int64, transfers []model.CreditTransfer)) *MockRepository_InsertTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].([]model.CreditTransfer))
	})
	return _c
}

func (_c *MockRepository_InsertTransactions_Call) Return(_a0 error) *MockRepository_InsertTransactions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_InsertTransactions_Call) RunAndReturn(run func(context.Context, int64, int64, []model.CreditTransfer) error) *MockRepository_InsertTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// RecordIdempotency provides a mock function with given fields: ctx, key, status
func (_m *MockRepository) RecordIdempotency(ctx context.Context, key string, status int) error {
	ret := _m.Called(ctx, key, status)

	if len(ret) == 0 {
		panic("no return value specified for RecordIdempotency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, key, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RecordIdempotency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordIdempotency'
type MockRepository_RecordIdempotency_Call struct {
	*mock.Call
}

// RecordIdempotency is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - status int
func (_e *MockRepository_Expecter) RecordIdempotency(ctx interface{}, key interface{}, status interface{}) *MockRepository_RecordIdempotency_Call {
	return &MockRepository_RecordIdempotency_Call{Call: _e.mock.On("RecordIdempotency", ctx, key, status)}
}

func (_c *MockRepository_RecordIdempotency_Call) Run(run func(ctx context.Context, key string, status int)) *MockRepository_RecordIdempotency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_RecordIdempotency_Call) Return(_a0 error) *MockRepository_RecordIdempotency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RecordIdempotency_Call) RunAndReturn(run func(context.Context, string, int) error) *MockRepository_RecordIdempotency_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionHistoryPage provides a mock function with given fields: ctx, accountID, cursor, limit
func (_m *MockRepository) TransactionHistoryPage(ctx context.Context, accountID int64, cursor model.Cursor, limit int) ([]model.TransactionHistoryItem, error) {
	ret := _m.Called(ctx, accountID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for TransactionHistoryPage")
	}

	var r0 []model.TransactionHistoryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, model.Cursor, int) ([]model.TransactionHistoryItem, error)); ok {
		return rf(ctx, accountID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, model.Cursor, int) []model.TransactionHistoryItem); ok {
		r0 = rf(ctx, accountID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TransactionHistoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, model.Cursor, int) error); ok {
		r1 = rf(ctx, accountID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_TransactionHistoryPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionHistoryPage'
type MockRepository_TransactionHistoryPage_Call struct {
	*mock.Call
}

// TransactionHistoryPage is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
//   - cursor model.Cursor
//   - limit int
func (_e *MockRepository_Expecter) TransactionHistoryPage(ctx interface{}, accountID interface{}, cursor interface{}, limit interface{}) *MockRepository_TransactionHistoryPage_Call {
	return &MockRepository_TransactionHistoryPage_Call{Call: _e.mock.On("TransactionHistoryPage", ctx, accountID, cursor, limit)}
}

func (_c *MockRepository_TransactionHistoryPage_Call) Run(run func(ctx context.Context, accountID int64, cursor model.Cursor, limit int)) *MockRepository_TransactionHistoryPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(model.Cursor), args[3].(int))
	})
	return _c
}

func (_c *MockRepository_TransactionHistoryPage_Call) Return(_a0 []model.TransactionHistoryItem, _a1 error) *MockRepository_TransactionHistoryPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_TransactionHistoryPage_Call) RunAndReturn(run func(context.Context, int64, model.Cursor, int) ([]model.TransactionHistoryItem, error)) *MockRepository_TransactionHistoryPage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
